import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  Building2, 
  Send, 
  UploadCloud, 
  Sparkles, 
  CheckCircle2, 
  AlertCircle, 
  ArrowLeft,
  Image as ImageIcon,
  X
} from 'lucide-react';
import api from '../services/api';
import { useAuth } from '../context/AuthContext';
import CategoryBadge from '../components/CategoryBadge';
import UrgencyBadge from '../components/UrgencyBadge';

export const SubmitComplaint = () => {
  const navigate = useNavigate();
  const { user } = useAuth();

  const [residentName, setResidentName] = useState(user?.name || 'Rajesh Sharma');
  const [flatNumber, setFlatNumber] = useState(user?.flat || 'B-402');
  const [description, setDescription] = useState('');
  const [selectedFile, setSelectedFile] = useState(null);
  const [previewUrl, setPreviewUrl] = useState(null);
  
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState(null);
  const [successData, setSuccessData] = useState(null);

  // Quick preset samples for fast hackathon demo / evaluation
  const demoSamples = [
    {
      title: 'Hinglish Water Issue',
      text: 'B wing main water pump trip ho gaya hai. Subah se taps are completely dry, please electrician bhejkar jaldi theek karwayein.'
    },
    {
      title: 'Lift Jerking Issue',
      text: 'Tower A lift 2 floor 4 pe jerk le rahi hai and squeaking noise bohot zyada hai. Bacche dar rahe hain enter karne me.'
    },
    {
      title: 'Ramp Blocked (Parking)',
      text: 'White Swift MH-12-AB-3421 is parked right in front of Tower C ramp, blocking wheelchair and stretcher access.'
    }
  ];

  const handleFileChange = (e) => {
    const file = e.target.files?.[0];
    if (file) {
      setSelectedFile(file);
      const url = URL.createObjectURL(file);
      setPreviewUrl(url);
    }
  };

  const removeFile = () => {
    setSelectedFile(null);
    if (previewUrl) URL.revokeObjectURL(previewUrl);
    setPreviewUrl(null);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!residentName.trim() || !flatNumber.trim() || !description.trim()) {
      setError('Please fill in all required fields.');
      return;
    }

    try {
      setSubmitting(true);
      setError(null);

      const payload = {
        resident_name: residentName.trim(),
        flat_number: flatNumber.trim().toUpperCase(),
        description: description.trim()
        // Note: category and urgency are deliberately omitted here per specification,
        // as they are generated by AI triage backend service.
      };

      const result = await api.createComplaint(payload);
      setSuccessData(result);
    } catch (err) {
      setError(err.message || 'Failed to submit complaint. Please check your backend connection.');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      {/* Back button */}
      <button
        type="button"
        onClick={() => navigate(-1)}
        className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-500 hover:text-slate-800 transition mb-6"
      >
        <ArrowLeft className="w-4 h-4" />
        <span>Back</span>
      </button>

      {/* Main Form Container */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6 sm:p-8">
        {/* Header */}
        <div className="border-b border-slate-100 pb-5 mb-6">
          <div className="flex items-center gap-2 mb-1">
            <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-blue-50 text-blue-700 border border-blue-200">
              Lodge Issue
            </span>
            <span className="text-xs text-slate-400">Phase 1 Foundation</span>
          </div>
          <h1 className="text-2xl font-bold text-slate-900 tracking-tight">
            Submit a Society Complaint
          </h1>
          <p className="text-xs sm:text-sm text-slate-500 mt-1">
            Describe the problem clearly. You can submit in English, Hindi, or Hinglish.
          </p>
        </div>

        {/* AI Triage Banner - Explicitly explains why no manual category/urgency is required */}
        <div className="mb-6 p-4 rounded-xl bg-gradient-to-r from-blue-50 to-indigo-50 border border-blue-100 flex items-start gap-3">
          <Sparkles className="w-5 h-5 text-blue-600 shrink-0 mt-0.5" />
          <div className="text-xs sm:text-sm text-slate-700 leading-relaxed">
            <strong className="text-blue-900 font-semibold block mb-0.5">
              Automated AI Triage Enabled
            </strong>
            You don't need to choose category or urgency levels manually. Our triage engine detects the domain (Water, Lift, Parking, etc.), measures criticality, and clusters duplicates automatically for the committee.
          </div>
        </div>

        {/* Success Confirmation Modal / Banner */}
        {successData && (
          <div className="mb-6 p-5 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-900">
            <div className="flex items-start gap-3">
              <CheckCircle2 className="w-6 h-6 text-emerald-600 shrink-0 mt-0.5" />
              <div className="flex-1">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <h3 className="text-base font-bold text-emerald-900">
                    Complaint Lodged Successfully!
                  </h3>
                  <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-emerald-100 text-emerald-800 border border-emerald-300">
                    <Sparkles className="w-3.5 h-3.5 text-emerald-700" />
                    AI analyzed
                  </span>
                </div>

                <p className="text-xs sm:text-sm text-emerald-800 mt-1">
                  Ticket ID: <strong className="font-mono bg-emerald-100/60 px-1.5 py-0.5 rounded">{successData.id}</strong> &bull; Flat <strong>{successData.flat_number}</strong>
                </p>

                {/* Structured AI Analysis Card */}
                <div className="mt-4 p-4 rounded-xl bg-white border border-emerald-200 shadow-xs space-y-3">
                  <div className="flex items-center justify-between pb-2 border-b border-slate-100">
                    <span className="text-xs font-bold text-slate-800 uppercase tracking-wider flex items-center gap-1.5">
                      <Sparkles className="w-4 h-4 text-blue-600" />
                      AI Analysis
                    </span>
                    <span className="text-[11px] text-slate-400 font-medium">
                      gemini-3.8-flash triage
                    </span>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                    <div>
                      <span className="text-[11px] text-slate-400 font-semibold uppercase tracking-wider block">Category</span>
                      <div className="mt-1">
                        <CategoryBadge category={successData.category} size="sm" />
                      </div>
                    </div>
                    <div>
                      <span className="text-[11px] text-slate-400 font-semibold uppercase tracking-wider block">Urgency</span>
                      <div className="mt-1">
                        <UrgencyBadge urgency={successData.urgency} size="sm" />
                      </div>
                    </div>
                    <div>
                      <span className="text-[11px] text-slate-400 font-semibold uppercase tracking-wider block">Language</span>
                      <div className="mt-1">
                        <span className="inline-flex items-center text-xs font-medium text-slate-700 bg-slate-100 px-2 py-0.5 rounded border border-slate-200">
                          {successData.language || 'English'}
                        </span>
                      </div>
                    </div>
                  </div>

                  <div>
                    <span className="text-[11px] text-slate-400 font-semibold uppercase tracking-wider block mb-1">Summary</span>
                    <p className="text-xs text-slate-700 bg-slate-50 p-2.5 rounded-lg border border-slate-100 italic leading-relaxed">
                      "{successData.summary || successData.ai_summary}"
                    </p>
                  </div>

                  <div>
                    <span className="text-[11px] text-slate-400 font-semibold uppercase tracking-wider block mb-1">Suggested Action</span>
                    <p className="text-xs text-slate-700 bg-slate-50 p-2.5 rounded-lg border border-slate-100 flex items-start gap-1.5 leading-relaxed">
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 shrink-0 mt-0.5" />
                      <span>{successData.suggested_action}</span>
                    </p>
                  </div>
                </div>

                <div className="mt-4 flex gap-3">
                  <button
                    type="button"
                    onClick={() => navigate(`/complaints/${successData.id}`)}
                    className="px-4 py-2 text-xs font-semibold text-white bg-emerald-700 rounded-lg hover:bg-emerald-800 transition"
                  >
                    View Complaint Ticket
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      setSuccessData(null);
                      setDescription('');
                      removeFile();
                    }}
                    className="px-4 py-2 text-xs font-semibold text-emerald-800 bg-emerald-100 rounded-lg hover:bg-emerald-200 transition"
                  >
                    Lodge Another
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Error notification */}
        {error && (
          <div className="mb-6 p-4 rounded-xl bg-red-50 border border-red-200 text-red-700 text-xs sm:text-sm flex items-center gap-2">
            <AlertCircle className="w-5 h-5 text-red-500 shrink-0" />
            <span>{error}</span>
          </div>
        )}

        {/* Submission Form */}
        <form onSubmit={handleSubmit} className="space-y-5">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label htmlFor="residentName" className="block text-xs font-semibold text-slate-700 mb-1">
                Resident Name <span className="text-red-500">*</span>
              </label>
              <input
                id="residentName"
                type="text"
                required
                value={residentName}
                onChange={(e) => setResidentName(e.target.value)}
                placeholder="e.g. Rajesh Sharma"
                className="w-full px-3.5 py-2.5 text-sm rounded-lg border border-slate-300 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 bg-white"
              />
            </div>

            <div>
              <label htmlFor="flatNumber" className="block text-xs font-semibold text-slate-700 mb-1">
                Flat Number <span className="text-red-500">*</span>
              </label>
              <input
                id="flatNumber"
                type="text"
                required
                value={flatNumber}
                onChange={(e) => setFlatNumber(e.target.value.toUpperCase())}
                placeholder="e.g. B-402, A-101"
                className="w-full px-3.5 py-2.5 text-sm rounded-lg border border-slate-300 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 bg-white font-medium"
              />
            </div>
          </div>

          {/* Description */}
          <div>
            <div className="flex items-center justify-between mb-1">
              <label htmlFor="complaintDescription" className="block text-xs font-semibold text-slate-700">
                Complaint Description <span className="text-red-500">*</span>
              </label>
              <span className="text-[11px] text-slate-400">English, Hindi or Hinglish</span>
            </div>
            <textarea
              id="complaintDescription"
              required
              rows={4}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Explain the problem in detail. E.g. '5th floor corridor light fuse ho gayi hai' or 'Lift door stuck on 2nd floor'..."
              className="w-full px-3.5 py-2.5 text-sm rounded-lg border border-slate-300 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 bg-white leading-relaxed resize-y"
            />
          </div>

          {/* Quick Demo Fill Buttons */}
          <div className="p-3 bg-slate-50 rounded-xl border border-slate-200">
            <span className="block text-[11px] font-semibold text-slate-500 uppercase tracking-wider mb-2">
              Try a demo issue template:
            </span>
            <div className="flex flex-wrap gap-2">
              {demoSamples.map((sample, idx) => (
                <button
                  key={idx}
                  type="button"
                  onClick={() => setDescription(sample.text)}
                  className="px-2.5 py-1 text-xs rounded-md bg-white border border-slate-200 text-slate-700 hover:border-blue-300 hover:text-blue-600 transition"
                >
                  {sample.title}
                </button>
              ))}
            </div>
          </div>

          {/* Optional Image Upload Placeholder */}
          <div>
            <label className="block text-xs font-semibold text-slate-700 mb-1">
              Optional Photo / Evidence (Placeholder)
            </label>
            <p className="text-[11px] text-slate-500 mb-2">
              Attach a photo of the leakage, parking violation, or broken fixture.
            </p>

            {previewUrl ? (
              <div className="relative inline-block border border-slate-200 rounded-xl p-2 bg-slate-50">
                <img
                  src={previewUrl}
                  alt="Upload preview"
                  className="h-32 w-auto object-cover rounded-lg"
                />
                <button
                  type="button"
                  onClick={removeFile}
                  className="absolute top-3 right-3 p-1 rounded-full bg-slate-900/70 text-white hover:bg-slate-900"
                  aria-label="Remove image"
                >
                  <X className="w-4 h-4" />
                </button>
                <div className="mt-1 text-[11px] text-slate-500 truncate max-w-xs">
                  {selectedFile?.name}
                </div>
              </div>
            ) : (
              <label
                htmlFor="photoUpload"
                className="border-2 border-dashed border-slate-300 hover:border-blue-400 rounded-xl p-6 text-center cursor-pointer transition flex flex-col items-center justify-center bg-slate-50/50 hover:bg-slate-50"
              >
                <UploadCloud className="w-8 h-8 text-slate-400 mb-2" />
                <span className="text-xs font-semibold text-slate-700">
                  Click to choose a photo or drag & drop
                </span>
                <span className="text-[11px] text-slate-400 mt-0.5">
                  PNG, JPG, or JPEG up to 5MB
                </span>
                <input
                  id="photoUpload"
                  type="file"
                  accept="image/*"
                  onChange={handleFileChange}
                  className="hidden"
                />
              </label>
            )}
          </div>

          {/* Submit Button */}
          <div className="pt-2">
            <button
              type="submit"
              disabled={submitting}
              className="w-full inline-flex items-center justify-center gap-2 px-6 py-3 text-sm font-semibold text-white bg-blue-600 rounded-xl hover:bg-blue-700 transition shadow-sm disabled:opacity-50 disabled:cursor-not-allowed focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
            >
              {submitting ? (
                <>
                  <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                  <span>Analyzing your complaint...</span>
                </>
              ) : (
                <>
                  <Send className="w-4 h-4" />
                  <span>Submit Complaint</span>
                </>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default SubmitComplaint;
